Install collectd-mcelog package on RedHat
voxpupuli/puppet-collectd pull request #962
Opened 2020-11-11 10:57 UTC by uvNikita

#### Pull Request (PR) description
Similar to `collectd-sensors`, redhat systems need `collectd-mcelog` package to be installed.

#### This Pull Request (PR) fixes the following issues

2020-11-24 00:20 UTC, kenyon commented
This is missing `$_manage_package = pick($manage_package, $collectd::manage_package)` and `$package_install_options` should be a parameter. See https://github.com/voxpupuli/puppet-collectd/blob/f9f2e7d37e2d0d5669acc1908f764eb62d0ff792/manifests/plugin/apache.pp or https://github.com/voxpupuli/puppet-collectd/blob/f9f2e7d37e2d0d5669acc1908f764eb62d0ff792/manifests/plugin/lvm.pp for examples.

2020-11-24 00:22 UTC, kenyon requested changes
This is missing `$_manage_package = pick($manage_package, $collectd::manage_package)` and `$package_install_options` should be a parameter. See https://github.com/voxpupuli/puppet-collectd/blob/f9f2e7d37e2d0d5669acc1908f764eb62d0ff792/manifests/plugin/apache.pp or https://github.com/voxpupuli/puppet-collectd/blob/f9f2e7d37e2d0d5669acc1908f764eb62d0ff792/manifests/plugin/lvm.pp for examples. Also https://github.com/voxpupuli/puppet-collectd/blob/master/spec/classes/collectd_plugin_mcelog_spec.rb should be updated.

2020-12-16 10:04 UTC, uvNikita commented
@kenyon Thanks for the review!

I added `manage_package`, `package_install_options` parameters and added spec test for RedHat os family.

2020-12-17 08:07 UTC, kenyon requested changes

2020-12-17 08:07 UTC, kenyon commented on manifests/plugin/mcelog.pp
> +  Variant[Undef, Boolean] $manage_package = undef,
```suggestion
  Optional[Boolean] $manage_package = undef,
```
Isn't this saying the same thing?

2020-12-17 20:50 UTC, kenyon approved these changes

2020-12-17 20:52 UTC, merged